<?php $h = function ($valor) { return htmlspecialchars((string) ($valor ?? ""), ENT_QUOTES, "UTF-8"); }; ?>
<section class="caja-contenedor">
  <div class="caja-resumen">
    <article class="caja-indicador caja-indicador-ingreso"><i class="fas fa-arrow-up"></i><div><span>Total ingresos</span><strong>Bs. <?= number_format((float) $resumen["total_ingresos"], 2) ?></strong></div></article>
    <article class="caja-indicador caja-indicador-salida"><i class="fas fa-arrow-down"></i><div><span>Total salidas</span><strong>Bs. <?= number_format((float) $resumen["total_salidas"], 2) ?></strong></div></article>
    <article class="caja-indicador caja-indicador-saldo"><i class="fas fa-wallet"></i><div><span>Saldo actual</span><strong>Bs. <?= number_format((float) $resumen["saldo_actual"], 2) ?></strong></div></article>
  </div>
  <div class="caja-encabezado"><h1>Gestión de Caja Chica</h1><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalCaja"><i class="fas fa-plus"></i> Nuevo</button></div>
  <div class="card caja-card"><div class="card-body table-responsive">
    <table id="tablaCaja" class="table table-bordered table-hover">
      <thead><tr><th>Tipo</th><th>Concepto</th><th>Descripción</th><th>Cantidad</th><th>Usuario</th><th>Fecha</th><th>Estado</th><th>Acciones</th></tr></thead>
      <tbody><?php foreach ($movimientos as $movimiento): ?><tr>
        <td><span class="badge badge-<?= $movimiento["tipo"] === "Ingreso" ? "success" : "danger" ?>"><?= $h($movimiento["tipo"]) ?></span></td><td><?= $h($movimiento["concepto"]) ?></td><td><?= $h($movimiento["descripcion"] ?: "Sin descripción") ?></td><td>Bs. <?= number_format((float) $movimiento["cantidad"], 2) ?></td><td><?= $h($movimiento["nombre_usuario"]) ?></td><td><?= date("d/m/Y H:i", strtotime($movimiento["fecha_movimiento"])) ?></td><td><span class="badge badge-<?= (int) $movimiento["estado_caja"] === 1 ? "success" : "secondary" ?>"><?= (int) $movimiento["estado_caja"] === 1 ? "Activo" : "Anulado" ?></span></td>
        <td><?php if ((int) $movimiento["estado_caja"] === 1): ?><form method="POST" action="<?= $base_url ?>caja/anular" class="form-anular-caja"><input type="hidden" name="csrf_token" value="<?= $h($csrfToken) ?>"><input type="hidden" name="id_caja" value="<?= (int) $movimiento["id_caja"] ?>"><button type="submit" class="btn btn-sm btn-danger" title="Anular movimiento"><i class="fas fa-ban"></i></button></form><?php endif; ?></td>
      </tr><?php endforeach; ?></tbody>
    </table>
  </div></div>
</section>
<div class="modal fade" id="modalCaja" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><form method="POST" action="<?= $base_url ?>caja/registrar" class="modal-content"><input type="hidden" name="csrf_token" value="<?= $h($csrfToken) ?>"><div class="modal-header"><h5 class="modal-title">Nuevo movimiento</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="form-group"><label for="tipoCaja">Tipo</label><select id="tipoCaja" name="tipo" class="form-control" required><option value="Ingreso">Ingreso</option><option value="Salida">Salida</option></select></div><div class="form-group"><label for="conceptoCaja">Concepto</label><input id="conceptoCaja" name="concepto" class="form-control" maxlength="50" required></div><div class="form-group"><label for="descripcionCaja">Descripción</label><textarea id="descripcionCaja" name="descripcion" class="form-control" maxlength="200" rows="3"></textarea></div><div class="form-group"><label for="cantidadCaja">Cantidad</label><input id="cantidadCaja" type="number" name="cantidad" class="form-control" min="0.01" step="0.01" required></div><div class="form-group mb-0"><label for="fechaCaja">Fecha</label><input id="fechaCaja" type="datetime-local" name="fecha_movimiento" class="form-control" value="<?= date("Y-m-d\TH:i") ?>" required></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Guardar</button></div></form></div></div>
