<?php $h = fn($valor) => htmlspecialchars((string) $valor, ENT_QUOTES, "UTF-8"); ?>
<div class="entrega-encabezado">📦 Encomiendas Retiradas</div>
<div class="contenedor"><div class="card"><h2 class="tituloHistorial">🔴 Historial de Paquetes Retirados</h2><input type="text" id="buscar" placeholder="Buscar por nombre o celular..."><div id="resultados" style="margin-top:25px;">
<?php foreach ($paquetes as $paquete):
  $tipo = trim((string) $paquete["tipo"]);
  $etiqueta = strtolower($tipo) === "alfabeto" ? mb_strtoupper(mb_substr(trim($paquete["cliente"]), 0, 1, "UTF-8"), "UTF-8") : (strtolower($tipo) === "tiktok" ? ($paquete["codigo"] ?? "") : mb_strtoupper($tipo, "UTF-8"));
  $foto = !empty($paquete["foto"]) ? $base_url . "assets/img/paquetes/" . rawurlencode(basename($paquete["foto"])) : "";
?><div class="paquete" data-id="<?= (int) $paquete["id"] ?>"><div class="filaSuperior"><div><div class="nombreCliente">👤 <?= $h($paquete["cliente"]) ?></div><div class="detalle">📦 <?= $h($paquete["observaciones"]) ?></div></div><div class="codigoCaja"><?= $h($etiqueta) ?></div></div><div class="contenidoPaquete"><div class="datosExtra">🏷️ <b>Tipo:</b> <?= $h($tipo) ?><?php if (strtolower($tipo) === "tiktok"): ?><br>🏢 <b>Empresa:</b> <?= $h($paquete["empresa"]) ?><?php if (!empty($paquete["nota_caja"])): ?><br>📝 <b>Nota:</b> <?= $h($paquete["nota_caja"]) ?><?php endif; ?><?php endif; ?><br>📱 <b>Celular:</b> <?= $h($paquete["celular"] ?: "Sin registrar") ?><br>📅 <b>Recepción:</b> <?= date("d/m/Y H:i", strtotime($paquete["fecha_registro"])) ?><br>🔴 <b>Estado:</b> <span class="estadoRetirado">Retirado</span><div class="fechaRetiro">📅 Retirado: <?= !empty($paquete["fecha_retiro"]) ? date("d/m/Y H:i", strtotime($paquete["fecha_retiro"])) : "Fecha no registrada" ?></div><div class="motivoRetiro">📝 Motivo: <?= $h($paquete["motivo_retiro"]) ?></div></div><?php if (date("Y-m-d", strtotime($paquete["fecha_registro"])) === date("Y-m-d")): ?><div class="etiquetaHoy">HOY</div><?php endif; ?><div class="fotoPaquete"><?php if ($foto): ?><img src="<?= $h($foto) ?>" alt="Foto del paquete" style="width:100%;height:100%;object-fit:cover;border-radius:10px;"><?php else: ?>📷 Foto del paquete<?php endif; ?></div></div></div>
<?php endforeach; ?></div></div></div>
<script src="<?= $base_url ?>assets/js/modules/entrega/retirados.js"></script>
