<?php if (!empty($errorVista)): ?><div class="contenedor"><div class="card"><?= htmlspecialchars($errorVista, ENT_QUOTES, "UTF-8") ?></div></div><?php return; endif; $h = fn($valor) => htmlspecialchars((string) $valor, ENT_QUOTES, "UTF-8"); $foto = !empty($paquete["foto"]) ? $base_url . "assets/img/paquetes/" . rawurlencode(basename($paquete["foto"])) : ""; ?>
<div class="entrega-encabezado">📦 Detalle del Paquete</div>
<div class="contenedor"><div class="card">
  <?php if (!empty($_GET["mensaje"])) { ?><p class="alerta"><?= $h($_GET["mensaje"]) ?></p><?php } ?>
  <div class="contenidoDetalle"><div>
    <h2 style="margin-top:0;color:#16a34a;">👤 <?= $h($paquete["cliente"] ?: "Sin registrar") ?></h2><hr>
    <p><b>📦 Código de Caja:</b> <?= $h($paquete["codigo"] ?? "") ?></p><p><b>🏢 Empresa:</b> <?= $h($paquete["empresa"] ?: "Sin registrar") ?></p><p><b>🏷 Tipo:</b> <?= $h($paquete["tipo"] ?: "Sin registrar") ?></p><p><b>📱 Celular:</b> <?= $h($paquete["celular"] ?: "Sin registrar") ?></p><p><b>📝 Detalle:</b> <?= $h($paquete["observaciones"] ?: "Sin registrar") ?></p><p><b>📅 Fecha de recepción:</b> <?= $h($paquete["fecha_registro"]) ?></p><p><b>⏳ Días almacenado:</b> <?= (int) $dias ?> día<?= $dias !== 1 ? "s" : "" ?></p><p><b>Estado:</b> <?= $h($paquete["estado"]) ?></p><hr>
    <h3 style="color:#16a34a;">💰 Cobro</h3><p><b>Precio base:</b> <?= number_format($precioBase, 2) ?> Bs</p><p><b>Recargo:</b> <?= number_format($recargo, 2) ?> Bs</p><p style="font-size:22px;font-weight:bold;color:#16a34a;">Total a cobrar: <?= number_format($totalCobrar, 2) ?> Bs</p><hr>
    <?php if ($cobrado): ?><p class="cobroRealizado">✅ Cobro registrado<br>Medio: <?= $h($medioCobro) ?></p><?php else: ?><p style="color:#dc2626;font-size:20px;font-weight:bold;">❌ Pendiente de cobro</p><?php endif; ?>
  </div><div>
    <div class="fotoDetalle"><?php if ($foto): ?><img src="<?= $h($foto) ?>" alt="Foto del paquete"><?php else: ?>📷 Foto pendiente<?php endif; ?></div>
    <?php if (!$cobrado && $paquete["estado"] === "Pendiente"): ?><div class="accionesCobro"><div class="tituloCobro">💰 ¿Cómo recibió el pago?</div><form method="POST" action="<?= $base_url ?>entrega/cobrar"><input type="hidden" name="csrf_token" value="<?= $h($csrfToken) ?>"><input type="hidden" name="id" value="<?= (int) $paquete["id"] ?>"><input type="hidden" name="medio_cobro" value="Efectivo"><button type="submit" class="btnEfectivo">💵 EFECTIVO — <?= number_format($totalCobrar, 2) ?> Bs<span>COBRAR Y ENTREGAR</span></button></form><button type="button" onclick="mostrarConfirmacionQR()" class="btnQR">📱 QR — <?= number_format($totalCobrar, 2) ?> Bs<span>VERIFICAR COBRO</span></button></div><?php endif; ?>
    <?php if ($paquete["estado"] === "Pendiente"): ?><div class="botonRetirar"><button type="button" onclick="mostrarRetiro()">🔴 Retirar paquete</button></div><div id="formRetiro"><div class="titulo-retiro">⚠️ Retirar paquete</div><div>Esta acción <b>NO registra ningún cobro</b>. El paquete pasará al historial de retirados.</div><form method="POST" action="<?= $base_url ?>entrega/retirar"><input type="hidden" name="csrf_token" value="<?= $h($csrfToken) ?>"><input type="hidden" name="id" value="<?= (int) $paquete["id"] ?>"><label>Motivo del retiro:</label><textarea name="motivo_retiro" required maxlength="1000" placeholder="Ejemplo: La dueña retiró para envío"></textarea><div class="acciones-retiro"><button type="button" onclick="cancelarRetiro()">Cancelar</button><button type="submit">🔴 Confirmar retiro</button></div></form></div><?php endif; ?>
  </div></div>
</div></div>
<?php if (!$cobrado && $paquete["estado"] === "Pendiente"): ?><div id="modalQR" class="modalQR"><div class="modalQRContenido"><div class="modalQRTitulo">📱 Verificar cobro QR</div><p>Confirma que verificaste correctamente el ingreso de:</p><div class="montoQR"><?= number_format($totalCobrar, 2) ?> Bs</div><p class="advertenciaQR">⚠️ No confirmes si el pago todavía no aparece en la cuenta.</p><form method="POST" action="<?= $base_url ?>entrega/cobrar"><input type="hidden" name="csrf_token" value="<?= $h($csrfToken) ?>"><input type="hidden" name="id" value="<?= (int) $paquete["id"] ?>"><input type="hidden" name="medio_cobro" value="QR"><div class="botonesModalQR"><button type="button" onclick="cerrarConfirmacionQR()" class="btnCancelarQR">Cancelar</button><button type="submit" class="btnConfirmarQR">✅ COBRO VERIFICADO <?= number_format($totalCobrar, 2) ?> Bs</button></div></form></div></div><?php endif; ?>
<script src="<?= $base_url ?>assets/js/modules/entrega/detalle_entrega.js"></script>
